import React, { useState, useEffect } from 'react'
import { Box, TextField, Button, Dialog, DialogTitle, DialogContent, DialogActions, Chip, Typography, Card, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TablePagination, CircularProgress, MenuItem } from '@mui/material'
import { threatService } from '../services/api'
import toast from 'react-hot-toast'
import { FiTrash2, FiRefreshCw, FiSearch, FiSliders, FiArrowUpRight } from 'react-icons/fi'
const severityColors = { Critical:'#ff6678', High:'#ffb768', Medium:'#7688ff', Low:'#6ee7c7' }
const statusColors = { New:'#7688ff', Analyzing:'#ffb768', Resolved:'#6ee7c7', Dismissed:'#8491a4' }
export const Threats = () => {
 const [threats,setThreats]=useState([]),[loading,setLoading]=useState(true),[searchQuery,setSearchQuery]=useState(''),[page,setPage]=useState(0),[rowsPerPage,setRowsPerPage]=useState(10),[deleteDialog,setDeleteDialog]=useState({open:false,threat:null}),[statusDialog,setStatusDialog]=useState({open:false,threat:null}),[newStatus,setNewStatus]=useState('')
 const fetchThreats=async()=>{try{setLoading(true);const r=await threatService.getThreats();setThreats(r.data.data||[])}catch{toast.error('Failed to load threat findings')}finally{setLoading(false)}}
 useEffect(()=>{fetchThreats()},[])
 const search=async()=>{if(!searchQuery.trim())return fetchThreats();try{setLoading(true);const r=await threatService.searchThreats(searchQuery);setThreats(r.data.data||[]);setPage(0)}catch{toast.error('Search failed')}finally{setLoading(false)}}
 const update=async()=>{try{await threatService.updateThreatStatus(statusDialog.threat.id,newStatus);toast.success('Finding status updated');setStatusDialog({open:false,threat:null});fetchThreats()}catch{toast.error('Status update failed')}}
 const remove=async()=>{try{await threatService.deleteThreat(deleteDialog.threat.id);toast.success('Finding removed');setDeleteDialog({open:false,threat:null});fetchThreats()}catch{toast.error('Removal failed')}}
 const visible=threats.slice(page*rowsPerPage,page*rowsPerPage+rowsPerPage)
 return <Box sx={{p:{xs:2,md:4},maxWidth:1540,mx:'auto'}}><Box sx={{display:'flex',justifyContent:'space-between',alignItems:{xs:'flex-start',sm:'center'},flexDirection:{xs:'column',sm:'row'},gap:2,mb:3.5}}><Box><Typography className="eyebrow">Intelligence operations / findings</Typography><Typography className="page-title" sx={{mt:.6}}>Threat findings</Typography><Typography sx={{mt:1,fontSize:13,color:'#8290a5'}}>Review, classify and take action on enriched intelligence.</Typography></Box><Button startIcon={<FiRefreshCw/>} onClick={fetchThreats} disabled={loading} variant="outlined" sx={{borderColor:'#33445c',color:'#b9c6d8'}}>Refresh feed</Button></Box>
 <Card className="surface" sx={{p:1.4,mb:2,display:'flex',gap:1,alignItems:'center'}}><FiSearch color="#7688ff"/><TextField variant="standard" placeholder="Search IP address, domain, hash or indicator…" fullWidth value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} InputProps={{disableUnderline:true}} sx={{'& input':{fontSize:13,color:'#e7eef9'}}}/><Button onClick={search} variant="contained" sx={{bgcolor:'#6ee7c7',color:'#091018','&:hover':{bgcolor:'#94f0d6'}}}>Search</Button><Button sx={{color:'#91a1b7',minWidth:36,p:1}}><FiSliders/></Button></Card>
 <TableContainer component={Card} className="surface">{loading&&!threats.length?<Box sx={{p:8,textAlign:'center'}}><CircularProgress size={26}/></Box>:<><Table><TableHead><TableRow sx={{'& th':{borderColor:'#263448',color:'#75849a',fontSize:10,fontWeight:800,letterSpacing:'.08em',textTransform:'uppercase',py:1.7}}}><TableCell>Indicator</TableCell><TableCell>Type</TableCell><TableCell>Severity</TableCell><TableCell>Status</TableCell><TableCell>Risk score</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{visible.length?visible.map(t=>{const name=t.iocType==='IPv4'?t.ip:t.iocType==='Domain'?t.domain:t.hash||t.name;return <TableRow key={t.id} hover sx={{'& td':{borderColor:'#202d40',py:1.7},'&:hover':{bgcolor:'rgba(118,136,255,.035)'}}}><TableCell><Typography className="mono" sx={{fontSize:12,color:'#e6edf7'}}>{name}</Typography><Typography sx={{fontSize:10,color:'#718096',mt:.35}}>ID {t.id}</Typography></TableCell><TableCell><Chip label={t.iocType||'Indicator'} size="small" sx={{bgcolor:'#172132',color:'#9eafc5',fontSize:10}}/></TableCell><TableCell><Chip label={t.severity} size="small" sx={{bgcolor:`${severityColors[t.severity]||'#7688ff'}20`,color:severityColors[t.severity]||'#7688ff',fontWeight:800,fontSize:10}}/></TableCell><TableCell><Chip clickable onClick={()=>{setStatusDialog({open:true,threat:t});setNewStatus(t.status||'New')}} label={t.status} size="small" sx={{bgcolor:`${statusColors[t.status]||'#8491a4'}16`,color:statusColors[t.status]||'#8491a4',fontWeight:700,fontSize:10}}/></TableCell><TableCell><Typography className="mono" sx={{fontSize:12,color:(t.riskScore||0)>70?'#ff8795':'#d6dfeb'}}>{t.riskScore ?? '—'}</Typography></TableCell><TableCell align="right"><Button onClick={()=>setDeleteDialog({open:true,threat:t})} size="small" startIcon={<FiTrash2/>} sx={{color:'#ff8795',fontSize:11}}>Remove</Button></TableCell></TableRow>}) : <TableRow><TableCell colSpan={6} align="center" sx={{py:7,border:0}}><Typography sx={{color:'#7b899c'}}>No matching threat findings</Typography></TableCell></TableRow>}</TableBody></Table><TablePagination component="div" count={threats.length} page={page} rowsPerPage={rowsPerPage} onPageChange={(_,n)=>setPage(n)} onRowsPerPageChange={e=>{setRowsPerPage(+e.target.value);setPage(0)}} rowsPerPageOptions={[5,10,25]} sx={{borderTop:'1px solid #263448',color:'#a9b6c7','& .MuiTablePagination-selectIcon':{color:'#a9b6c7'}}}/></>}</TableContainer>
 <Dialog open={deleteDialog.open} onClose={()=>setDeleteDialog({open:false,threat:null})} PaperProps={{sx:{bgcolor:'#101723',color:'#e8edf7',border:'1px solid #2b3b51'}}}><DialogTitle sx={{fontWeight:800}}>Remove finding</DialogTitle><DialogContent><Typography sx={{color:'#a9b6c7'}}>This action cannot be undone. Remove this indicator from the workspace?</Typography></DialogContent><DialogActions sx={{p:2}}><Button onClick={()=>setDeleteDialog({open:false,threat:null})} sx={{color:'#a9b6c7'}}>Cancel</Button><Button variant="contained" onClick={remove} sx={{bgcolor:'#ff6678'}}>Remove</Button></DialogActions></Dialog>
 <Dialog open={statusDialog.open} onClose={()=>setStatusDialog({open:false,threat:null})} PaperProps={{sx:{bgcolor:'#101723',color:'#e8edf7',border:'1px solid #2b3b51',minWidth:300}}}><DialogTitle sx={{fontWeight:800}}>Update investigation status</DialogTitle><DialogContent><TextField select fullWidth value={newStatus} onChange={e=>setNewStatus(e.target.value)} sx={{mt:1}}>{['New','Analyzing','Resolved','Dismissed'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></DialogContent><DialogActions sx={{p:2}}><Button onClick={()=>setStatusDialog({open:false,threat:null})} sx={{color:'#a9b6c7'}}>Cancel</Button><Button variant="contained" onClick={update} sx={{bgcolor:'#6ee7c7',color:'#081018'}}>Update</Button></DialogActions></Dialog>
 </Box>
}
